### ISSUE TITLE
question about  kernels

### ISSUE THREAD

**Issue by zjin-lcf** [atmyers/GatherAndPushKernel#1]
I have some questions about your repository.

One file includes <AMReX_Particles.H>. The file is not in your repository. Is it standalone ?

In addition, is there a standalone GPU version for your kernel ?

Thanks

**Comment by atmyers** [comment]
Hello, 

This repository is not standalone - it requires the AMReX framework: https://github.com/AMReX-Codes/amrex/

The code in em_pic_K.H can be compiled either for GPU or CPU execution. 

This repo was made to share code with some collaborators, so it's not very well documented. You can find documentation and examples by following the links in the amrex repo.
